# Generated by Django 3.1 on 2020-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_imprezy', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('uczestnicy', models.PositiveSmallIntegerField(default=0)),
                ('cena', models.IntegerField(default=0)),
                ('instutucja', models.CharField(default='', max_length=100)),
                ('organizator', models.CharField(default='', max_length=100)),
                ('wyżywienie', models.CharField(default='', max_length=100)),
                ('przewoźnik', models.CharField(default='', max_length=100)),
                ('program', models.TextField(default='')),
                ('umowa', models.TextField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default='')),
                ('pliki', models.FileField(blank=True, null=True, upload_to='pliki')),
            ],
        ),
    ]
