# Generated by Django 3.1 on 2020-08-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.AddField(
            model_name='trip',
            name='cena',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='instutucja',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='nazwa_imprezy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='organizator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='program',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='przewoźnik',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='uczestnicy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='umowa',
            field=models.TextField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], default=''),
        ),
        migrations.AddField(
            model_name='trip',
            name='wyżywienie',
            field=models.CharField(default='', max_length=100),
        ),
    ]
